name: Check Bazzite Images

on:
  schedule:
    - cron: "42 */3 * * *"
  workflow_dispatch:

jobs:
  check-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: "bazzite-standard"
            image: "ghcr.io/ublue-os/bazzite-dx:stable"
            event: "bazzite-updated"
            file: ".bazzite_digest"
          - name: "bazzite-deck"
            image: "ghcr.io/ublue-os/bazzite-deck:stable"
            event: "bazzite-deck-updated"
            file: ".bazzite_digest_deck"

    steps:
      - name: Checkout repo (State Branch)
        uses: actions/checkout@v6
        with:
          ref: state

      - name: Fetch current digest
        id: remote
        run: |
          DIGEST=$(skopeo inspect docker://${{ matrix.image }} | jq -r '.Digest')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Compare and Save
        id: check
        run: |
          if [ -f "${{ matrix.file }}" ] && [ "$(cat ${{ matrix.file }})" == "${{ steps.remote.outputs.digest }}" ]; then
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "${{ steps.remote.outputs.digest }}" > "${{ matrix.file }}"
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Push update
        if: steps.check.outputs.updated == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ matrix.file }}
          git commit -m "Update ${{ matrix.name }} digest"
          git pull --rebase origin state
          git push origin state

      - name: Trigger build
        if: steps.check.outputs.updated == 'true'
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: ${{ matrix.event }}
